<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.automation.qa</groupId>
    <artifactId>automacao-quitacao</artifactId>
    <version>1.0.0</version>
    <name>Automation Framework</name>
    <description>Framework de Automação Web, API, SOAP e Banco de Dados</description>

    <properties>

        <!-- Java -->
        <java.version>21</java.version>
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Framework -->
        <playwright.version>1.54.0</playwright.version>

        <!-- Testes -->
        <junit.version>5.13.1</junit.version>
        <allure.version>2.29.1</allure.version>

        <!-- Banco -->
        <mssql.version>13.4.0.jre11</mssql.version>

        <!-- HTTP -->
        <httpclient.version>5.5.1</httpclient.version>

        <!-- REST -->
        <restassured.version>5.5.6</restassured.version>

        <!-- JSON -->
        <jackson.version>2.19.2</jackson.version>

        <!-- Assert -->
        <assertj.version>3.27.4</assertj.version>

        <!-- Logs -->
        <slf4j.version>2.0.18</slf4j.version>

    </properties>

    <dependencyManagement>

        <dependencies>

            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        </dependencies>

    </dependencyManagement>

    <dependencies>

        <!-- PLAYWRIGHT -->

        <dependency>
            <groupId>com.microsoft.playwright</groupId>
            <artifactId>playwright</artifactId>
            <version>${playwright.version}</version>
        </dependency>

        <!-- JUNIT -->

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- ALLURE -->

        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-junit5</artifactId>
            <version>${allure.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- REST ASSURED -->

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>${restassured.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- JACKSON -->

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <!-- SQL SERVER -->

        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>${mssql.version}</version>
        </dependency>

        <!-- SOAP -->

        <dependency>
            <groupId>org.apache.httpcomponents.client5</groupId>
            <artifactId>httpclient5</artifactId>
            <version>${httpclient.version}</version>
        </dependency>

        <!-- ASSERTJ -->

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertj.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- LOG -->

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
        </dependency>

    </dependencies>

    <build>

        <plugins>

            <plugin>

                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>

                <configuration>

                    <release>${java.version}</release>
                    <encoding>UTF-8</encoding>

                </configuration>

            </plugin>

            <plugin>

                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.3</version>

                <configuration>

                    <useModulePath>false</useModulePath>

                    <systemPropertyVariables>

                        <allure.results.directory>
                            ${project.build.directory}/allure-results
                        </allure.results.directory>

                    </systemPropertyVariables>

                </configuration>

            </plugin>

        </plugins>

    </build>

</project>