environment=hml

base.url=file:///C:/Users/User/IdeaProjects/automacao-quitacao/src/main/resources/quitacao.html

base.url.dev=file:///C:/Users/User/IdeaProjects/automacao-quitacao/src/main/resources/quitacao.html
base.url.hml=file:///C:/Users/User/IdeaProjects/automacao-quitacao/src/main/resources/quitacao.html
base.url.prod=file:///C:/Users/User/IdeaProjects/automacao-quitacao/src/main/resources/quitacao.html

browser=chrome
headless=false

viewport.width=1920
viewport.height=1080

login.usuario=student
login.senha=Password123